[versions]
agp = "9.2.1"
kotlin = "2.2.10"
kotlinxCoroutines = "1.10.1"
kotlinxSerializationJson = "1.9.0"
ksp = "2.2.10-2.0.2"
coreKtx = "1.17.0"
lifecycle = "2.9.3"
compileSdk = "36"
minSdk = "30"
targetSdk = "36"
buildTools = "36.1.0"

activityCompose = "1.10.1"
composeBom = "2025.08.01"
appcompat = "1.7.1"
koin = "4.1.1"
couchbase = "3.2.4"
gson = "2.13.1"
playServicesWearables = "19.0.0"
room = "2.8.1"
wearCompose = "1.5.0"
wearInput = "1.2.0"
wearToolingPreview = "1.0.0"
composeMaterialIconsExtended = "1.7.7"

junit = "4.13.2"
composeFoundation = "1.5.0"
coreSplashscreen = "1.0.1"

okhttp = "5.1.0"

[libraries]
#androidx
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activityCompose" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-service = { group = "androidx.lifecycle", name = "lifecycle-service", version.ref = "lifecycle" }

#room
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "room" }

#compose
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
compose-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle" }
compose-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "composeMaterialIconsExtended" }

#wear-compose
wear-compose-material = { group = "androidx.wear.compose", name = "compose-material", version.ref = "wearCompose" }
wear-input = { group = "androidx.wear", name = "wear-input", version.ref = "wearInput" }
wear-tooling-preview = { group = "androidx.wear", name = "wear-tooling-preview", version.ref = "wearToolingPreview" }
androidx-compose-foundation = { group = "androidx.wear.compose", name = "compose-foundation", version.ref = "composeFoundation" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "coreSplashscreen" }

#coroutines / serialization
kotlinx-coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "kotlinxCoroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }

#koin
koin-core = { module = "io.insert-koin:koin-core" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }

#wearable data layer
android-gms-wearable = { group = "com.google.android.gms", name = "play-services-wearable", version.ref = "playServicesWearables" }

#storage
couchbase = { group = "com.couchbase.lite", name = "couchbase-lite-android-ktx", version.ref = "couchbase" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

#network
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }

# plugin Dependencies of the included build-logic
android-gradle-plugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradle-plugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }

[bundles]
compose = [
    "compose-activity",
    "compose-runtime",
    "compose-lifecycle-runtime",
    "compose-lifecycle-viewmodel",
    "compose-ui",
    "compose-ui-graphics",
    "compose-ui-tooling",
    "compose-ui-tooling-preview",
    "compose-material3",
    "compose-material-icons-extended",
]
androidx = [
    "androidx-core-ktx",
    "androidx-appcompat",
    "androidx-lifecycle-runtime-ktx",
]
koin = [
    "koin-android",
    "koin-core",
    "koin-androidx-compose",
]

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinCompose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
